"""
IPL 2025 static data - teams, players, schedule, and default members.
"""

TEAMS = [
    {
        "id": "csk",
        "name": "Chennai Super Kings",
        "shortName": "CSK",
        "color": "#FCCA06",
        "logo": "https://ui-avatars.com/api/?name=CSK&background=FCCA06&color=000&size=128&bold=true&font-size=0.5&rounded=true",
        "captain": "Ruturaj Gaikwad",
        "homeGround": "MA Chidambaram Stadium, Chennai",
        "players": [
            {"name": "Ruturaj Gaikwad", "role": "Batter", "country": "India"},
            {"name": "Devon Conway", "role": "Batter", "country": "New Zealand"},
            {"name": "Rahul Tripathi", "role": "Batter", "country": "India"},
            {"name": "Shivam Dube", "role": "All-rounder", "country": "India"},
            {"name": "Ravindra Jadeja", "role": "All-rounder", "country": "India"},
            {"name": "MS Dhoni", "role": "Wicket-keeper", "country": "India"},
            {"name": "Deepak Chahar", "role": "Bowler", "country": "India"},
            {"name": "Matheesha Pathirana", "role": "Bowler", "country": "Sri Lanka"},
            {"name": "Tushar Deshpande", "role": "Bowler", "country": "India"},
            {"name": "Rachin Ravindra", "role": "All-rounder", "country": "New Zealand"},
            {"name": "Khaleel Ahmed", "role": "Bowler", "country": "India"},
        ]
    },
    {
        "id": "mi",
        "name": "Mumbai Indians",
        "shortName": "MI",
        "color": "#004BA0",
        "logo": "https://ui-avatars.com/api/?name=MI&background=004BA0&color=fff&size=128&bold=true&font-size=0.5&rounded=true",
        "captain": "Hardik Pandya",
        "homeGround": "Wankhede Stadium, Mumbai",
        "players": [
            {"name": "Rohit Sharma", "role": "Batter", "country": "India"},
            {"name": "Ishan Kishan", "role": "Wicket-keeper", "country": "India"},
            {"name": "Suryakumar Yadav", "role": "Batter", "country": "India"},
            {"name": "Hardik Pandya", "role": "All-rounder", "country": "India"},
            {"name": "Tim David", "role": "All-rounder", "country": "Australia"},
            {"name": "Tilak Varma", "role": "Batter", "country": "India"},
            {"name": "Jasprit Bumrah", "role": "Bowler", "country": "India"},
            {"name": "Trent Boult", "role": "Bowler", "country": "New Zealand"},
            {"name": "Piyush Chawla", "role": "Bowler", "country": "India"},
            {"name": "Naman Dhir", "role": "All-rounder", "country": "India"},
            {"name": "Deepak Chahar", "role": "Bowler", "country": "India"},
        ]
    },
    {
        "id": "rcb",
        "name": "Royal Challengers Bengaluru",
        "shortName": "RCB",
        "color": "#EC1C24",
        "logo": "https://ui-avatars.com/api/?name=RCB&background=EC1C24&color=fff&size=128&bold=true&font-size=0.5&rounded=true",
        "captain": "Rajat Patidar",
        "homeGround": "M. Chinnaswamy Stadium, Bengaluru",
        "players": [
            {"name": "Virat Kohli", "role": "Batter", "country": "India"},
            {"name": "Rajat Patidar", "role": "Batter", "country": "India"},
            {"name": "Phil Salt", "role": "Wicket-keeper", "country": "England"},
            {"name": "Liam Livingstone", "role": "All-rounder", "country": "England"},
            {"name": "Krunal Pandya", "role": "All-rounder", "country": "India"},
            {"name": "Jitesh Sharma", "role": "Wicket-keeper", "country": "India"},
            {"name": "Bhuvneshwar Kumar", "role": "Bowler", "country": "India"},
            {"name": "Josh Hazlewood", "role": "Bowler", "country": "Australia"},
            {"name": "Yash Dayal", "role": "Bowler", "country": "India"},
            {"name": "Rasikh Salam", "role": "Bowler", "country": "India"},
        ]
    },
    {
        "id": "kkr",
        "name": "Kolkata Knight Riders",
        "shortName": "KKR",
        "color": "#3A225D",
        "logo": "https://ui-avatars.com/api/?name=KKR&background=3A225D&color=FFB800&size=128&bold=true&font-size=0.5&rounded=true",
        "captain": "Ajinkya Rahane",
        "homeGround": "Eden Gardens, Kolkata",
        "players": [
            {"name": "Ajinkya Rahane", "role": "Batter", "country": "India"},
            {"name": "Venkatesh Iyer", "role": "All-rounder", "country": "India"},
            {"name": "Rinku Singh", "role": "Batter", "country": "India"},
            {"name": "Andre Russell", "role": "All-rounder", "country": "West Indies"},
            {"name": "Sunil Narine", "role": "All-rounder", "country": "West Indies"},
            {"name": "Quinton de Kock", "role": "Wicket-keeper", "country": "South Africa"},
            {"name": "Varun Chakravarthy", "role": "Bowler", "country": "India"},
            {"name": "Harshit Rana", "role": "Bowler", "country": "India"},
            {"name": "Mitchell Starc", "role": "Bowler", "country": "Australia"},
            {"name": "Ramandeep Singh", "role": "All-rounder", "country": "India"},
        ]
    },
    {
        "id": "dc",
        "name": "Delhi Capitals",
        "shortName": "DC",
        "color": "#17479E",
        "logo": "https://ui-avatars.com/api/?name=DC&background=17479E&color=fff&size=128&bold=true&font-size=0.5&rounded=true",
        "captain": "KL Rahul",
        "homeGround": "Arun Jaitley Stadium, Delhi",
        "players": [
            {"name": "KL Rahul", "role": "Wicket-keeper", "country": "India"},
            {"name": "Jake Fraser-McGurk", "role": "Batter", "country": "Australia"},
            {"name": "Tristan Stubbs", "role": "Batter", "country": "South Africa"},
            {"name": "Axar Patel", "role": "All-rounder", "country": "India"},
            {"name": "Mitchell Marsh", "role": "All-rounder", "country": "Australia"},
            {"name": "Kuldeep Yadav", "role": "Bowler", "country": "India"},
            {"name": "Mukesh Kumar", "role": "Bowler", "country": "India"},
            {"name": "T Natarajan", "role": "Bowler", "country": "India"},
            {"name": "Faf du Plessis", "role": "Batter", "country": "South Africa"},
            {"name": "Abishek Porel", "role": "Wicket-keeper", "country": "India"},
        ]
    },
    {
        "id": "pbks",
        "name": "Punjab Kings",
        "shortName": "PBKS",
        "color": "#ED1B24",
        "logo": "https://ui-avatars.com/api/?name=PBKS&background=ED1B24&color=fff&size=128&bold=true&font-size=0.45&rounded=true",
        "captain": "Shreyas Iyer",
        "homeGround": "IS Bindra Stadium, Mohali",
        "players": [
            {"name": "Shreyas Iyer", "role": "Batter", "country": "India"},
            {"name": "Prabhsimran Singh", "role": "Wicket-keeper", "country": "India"},
            {"name": "Shashank Singh", "role": "All-rounder", "country": "India"},
            {"name": "Marcus Stoinis", "role": "All-rounder", "country": "Australia"},
            {"name": "Glenn Maxwell", "role": "All-rounder", "country": "Australia"},
            {"name": "Arshdeep Singh", "role": "Bowler", "country": "India"},
            {"name": "Kagiso Rabada", "role": "Bowler", "country": "South Africa"},
            {"name": "Yuzvendra Chahal", "role": "Bowler", "country": "India"},
            {"name": "Marco Jansen", "role": "Bowler", "country": "South Africa"},
            {"name": "Nehal Wadhera", "role": "Batter", "country": "India"},
        ]
    },
    {
        "id": "rr",
        "name": "Rajasthan Royals",
        "shortName": "RR",
        "color": "#EA1A85",
        "logo": "https://ui-avatars.com/api/?name=RR&background=EA1A85&color=fff&size=128&bold=true&font-size=0.5&rounded=true",
        "captain": "Sanju Samson",
        "homeGround": "Sawai Mansingh Stadium, Jaipur",
        "players": [
            {"name": "Sanju Samson", "role": "Wicket-keeper", "country": "India"},
            {"name": "Yashasvi Jaiswal", "role": "Batter", "country": "India"},
            {"name": "Riyan Parag", "role": "All-rounder", "country": "India"},
            {"name": "Shimron Hetmyer", "role": "Batter", "country": "West Indies"},
            {"name": "Dhruv Jurel", "role": "Wicket-keeper", "country": "India"},
            {"name": "Wanindu Hasaranga", "role": "All-rounder", "country": "Sri Lanka"},
            {"name": "Sandeep Sharma", "role": "Bowler", "country": "India"},
            {"name": "Trent Boult", "role": "Bowler", "country": "New Zealand"},
            {"name": "Jofra Archer", "role": "Bowler", "country": "England"},
            {"name": "Maheesh Theekshana", "role": "Bowler", "country": "Sri Lanka"},
        ]
    },
    {
        "id": "srh",
        "name": "Sunrisers Hyderabad",
        "shortName": "SRH",
        "color": "#FF822A",
        "logo": "https://ui-avatars.com/api/?name=SRH&background=FF822A&color=000&size=128&bold=true&font-size=0.5&rounded=true",
        "captain": "Pat Cummins",
        "homeGround": "Rajiv Gandhi Intl. Stadium, Hyderabad",
        "players": [
            {"name": "Travis Head", "role": "Batter", "country": "Australia"},
            {"name": "Abhishek Sharma", "role": "All-rounder", "country": "India"},
            {"name": "Heinrich Klaasen", "role": "Wicket-keeper", "country": "South Africa"},
            {"name": "Pat Cummins", "role": "Bowler", "country": "Australia"},
            {"name": "Nitish Reddy", "role": "All-rounder", "country": "India"},
            {"name": "Ishan Kishan", "role": "Wicket-keeper", "country": "India"},
            {"name": "Mohammed Shami", "role": "Bowler", "country": "India"},
            {"name": "Harshal Patel", "role": "Bowler", "country": "India"},
            {"name": "Adam Zampa", "role": "Bowler", "country": "Australia"},
            {"name": "Rahul Chahar", "role": "Bowler", "country": "India"},
        ]
    },
    {
        "id": "gt",
        "name": "Gujarat Titans",
        "shortName": "GT",
        "color": "#1C1C1C",
        "logo": "https://ui-avatars.com/api/?name=GT&background=1C1C1C&color=FFB800&size=128&bold=true&font-size=0.5&rounded=true",
        "captain": "Shubman Gill",
        "homeGround": "Narendra Modi Stadium, Ahmedabad",
        "players": [
            {"name": "Shubman Gill", "role": "Batter", "country": "India"},
            {"name": "Jos Buttler", "role": "Wicket-keeper", "country": "England"},
            {"name": "Sai Sudharsan", "role": "Batter", "country": "India"},
            {"name": "Rashid Khan", "role": "Bowler", "country": "Afghanistan"},
            {"name": "Kagiso Rabada", "role": "Bowler", "country": "South Africa"},
            {"name": "Washington Sundar", "role": "All-rounder", "country": "India"},
            {"name": "Rahul Tewatia", "role": "All-rounder", "country": "India"},
            {"name": "Mohammed Siraj", "role": "Bowler", "country": "India"},
            {"name": "Shahrukh Khan", "role": "All-rounder", "country": "India"},
            {"name": "Gerald Coetzee", "role": "Bowler", "country": "South Africa"},
        ]
    },
    {
        "id": "lsg",
        "name": "Lucknow Super Giants",
        "shortName": "LSG",
        "color": "#A72056",
        "logo": "https://ui-avatars.com/api/?name=LSG&background=A72056&color=fff&size=128&bold=true&font-size=0.5&rounded=true",
        "captain": "Rishabh Pant",
        "homeGround": "BRSABV Ekana Stadium, Lucknow",
        "players": [
            {"name": "Rishabh Pant", "role": "Wicket-keeper", "country": "India"},
            {"name": "David Miller", "role": "Batter", "country": "South Africa"},
            {"name": "Nicholas Pooran", "role": "Wicket-keeper", "country": "West Indies"},
            {"name": "Aiden Markram", "role": "Batter", "country": "South Africa"},
            {"name": "Mitchell Marsh", "role": "All-rounder", "country": "Australia"},
            {"name": "Ravi Bishnoi", "role": "Bowler", "country": "India"},
            {"name": "Avesh Khan", "role": "Bowler", "country": "India"},
            {"name": "Mohsin Khan", "role": "Bowler", "country": "India"},
            {"name": "Ayush Badoni", "role": "Batter", "country": "India"},
            {"name": "Mayank Yadav", "role": "Bowler", "country": "India"},
        ]
    }
]

# IPL 2025 Schedule (sample matches)
SCHEDULE = [
    {"matchNo": 1, "date": "2025-03-22", "time": "19:30", "team1": "kkr", "team2": "rcb", "venue": "Eden Gardens, Kolkata", "status": "completed", "result": "KKR won by 7 wickets", "team1Score": "174/8", "team2Score": "178/3"},
    {"matchNo": 2, "date": "2025-03-23", "time": "15:30", "team1": "srh", "team2": "rr", "venue": "Rajiv Gandhi Intl. Stadium", "status": "completed", "result": "SRH won by 23 runs", "team1Score": "198/5", "team2Score": "175/9"},
    {"matchNo": 3, "date": "2025-03-23", "time": "19:30", "team1": "csk", "team2": "mi", "venue": "MA Chidambaram Stadium", "status": "completed", "result": "CSK won by 5 wickets", "team1Score": "165/7", "team2Score": "168/5"},
    {"matchNo": 4, "date": "2025-03-24", "time": "19:30", "team1": "dc", "team2": "lsg", "venue": "Arun Jaitley Stadium", "status": "completed", "result": "LSG won by 2 wickets", "team1Score": "187/4", "team2Score": "190/8"},
    {"matchNo": 5, "date": "2025-03-25", "time": "19:30", "team1": "gt", "team2": "pbks", "venue": "Narendra Modi Stadium", "status": "completed", "result": "PBKS won by 6 runs", "team1Score": "162/8", "team2Score": "168/6"},
    {"matchNo": 6, "date": "2025-03-26", "time": "19:30", "team1": "rcb", "team2": "csk", "venue": "M. Chinnaswamy Stadium", "status": "completed", "result": "RCB won by 4 wickets", "team1Score": "180/6", "team2Score": "184/6"},
    {"matchNo": 7, "date": "2025-03-27", "time": "19:30", "team1": "mi", "team2": "kkr", "venue": "Wankhede Stadium", "status": "completed", "result": "MI won by 34 runs", "team1Score": "205/4", "team2Score": "171/10"},
    {"matchNo": 8, "date": "2025-03-28", "time": "19:30", "team1": "rr", "team2": "dc", "venue": "Sawai Mansingh Stadium", "status": "completed", "result": "RR won by 5 wickets", "team1Score": "156/9", "team2Score": "159/5"},
    {"matchNo": 9, "date": "2025-03-29", "time": "15:30", "team1": "lsg", "team2": "gt", "venue": "BRSABV Ekana Stadium", "status": "completed", "result": "LSG won by 8 wickets", "team1Score": "145/10", "team2Score": "146/2"},
    {"matchNo": 10, "date": "2025-03-29", "time": "19:30", "team1": "pbks", "team2": "srh", "venue": "IS Bindra Stadium", "status": "completed", "result": "PBKS won by 11 runs", "team1Score": "189/5", "team2Score": "178/7"},
    {"matchNo": 11, "date": "2025-03-30", "time": "15:30", "team1": "csk", "team2": "dc", "venue": "MA Chidambaram Stadium", "status": "completed", "result": "CSK won by 32 runs", "team1Score": "210/3", "team2Score": "178/8"},
    {"matchNo": 12, "date": "2025-03-30", "time": "19:30", "team1": "kkr", "team2": "rr", "venue": "Eden Gardens", "status": "completed", "result": "KKR won by 6 wickets", "team1Score": "155/8", "team2Score": "158/4"},
    {"matchNo": 13, "date": "2025-03-31", "time": "19:30", "team1": "mi", "team2": "rcb", "venue": "Wankhede Stadium", "status": "completed", "result": "RCB won by 3 wickets", "team1Score": "196/5", "team2Score": "199/7"},
    {"matchNo": 14, "date": "2025-04-01", "time": "19:30", "team1": "srh", "team2": "gt", "venue": "Rajiv Gandhi Intl. Stadium", "status": "completed", "result": "SRH won by 45 runs", "team1Score": "225/3", "team2Score": "180/10"},
    {"matchNo": 15, "date": "2025-04-02", "time": "19:30", "team1": "pbks", "team2": "csk", "venue": "IS Bindra Stadium", "status": "completed", "result": "CSK won by 7 wickets", "team1Score": "170/7", "team2Score": "173/3"},
    {"matchNo": 16, "date": "2025-04-03", "time": "19:30", "team1": "dc", "team2": "mi", "venue": "Arun Jaitley Stadium", "status": "completed", "result": "DC won by 19 runs", "team1Score": "192/6", "team2Score": "173/9"},
    {"matchNo": 17, "date": "2025-04-04", "time": "19:30", "team1": "rr", "team2": "lsg", "venue": "Sawai Mansingh Stadium", "status": "completed", "result": "RR won by 22 runs", "team1Score": "188/4", "team2Score": "166/8"},
    {"matchNo": 18, "date": "2025-04-05", "time": "15:30", "team1": "gt", "team2": "kkr", "venue": "Narendra Modi Stadium", "status": "completed", "result": "KKR won by 5 runs", "team1Score": "172/6", "team2Score": "177/7"},
    {"matchNo": 19, "date": "2025-04-05", "time": "19:30", "team1": "rcb", "team2": "srh", "venue": "M. Chinnaswamy Stadium", "status": "completed", "result": "RCB won by 15 runs", "team1Score": "206/4", "team2Score": "191/7"},

    # Upcoming matches
    {"matchNo": 20, "date": "2025-04-06", "time": "15:30", "team1": "lsg", "team2": "pbks", "venue": "BRSABV Ekana Stadium", "status": "live", "result": None, "team1Score": "142/4 (16.2)", "team2Score": None, "liveDetail": {"batting": "lsg", "currentOver": "16.2", "crr": "8.69", "lastWicket": "Aiden Markram c Stoinis b Rabada 32(21)"}},
    {"matchNo": 21, "date": "2025-04-06", "time": "19:30", "team1": "mi", "team2": "dc", "venue": "Wankhede Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 22, "date": "2025-04-07", "time": "19:30", "team1": "csk", "team2": "rr", "venue": "MA Chidambaram Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 23, "date": "2025-04-08", "time": "19:30", "team1": "kkr", "team2": "srh", "venue": "Eden Gardens", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 24, "date": "2025-04-09", "time": "19:30", "team1": "rcb", "team2": "gt", "venue": "M. Chinnaswamy Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 25, "date": "2025-04-10", "time": "19:30", "team1": "pbks", "team2": "mi", "venue": "IS Bindra Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 26, "date": "2025-04-11", "time": "19:30", "team1": "dc", "team2": "kkr", "venue": "Arun Jaitley Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 27, "date": "2025-04-12", "time": "15:30", "team1": "srh", "team2": "csk", "venue": "Rajiv Gandhi Intl. Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 28, "date": "2025-04-12", "time": "19:30", "team1": "rr", "team2": "rcb", "venue": "Sawai Mansingh Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 29, "date": "2025-04-13", "time": "15:30", "team1": "gt", "team2": "lsg", "venue": "Narendra Modi Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 30, "date": "2025-04-13", "time": "19:30", "team1": "mi", "team2": "srh", "venue": "Wankhede Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},

    # More upcoming
    {"matchNo": 31, "date": "2025-04-14", "time": "19:30", "team1": "csk", "team2": "kkr", "venue": "MA Chidambaram Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 32, "date": "2025-04-15", "time": "19:30", "team1": "pbks", "team2": "dc", "venue": "IS Bindra Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 33, "date": "2025-04-16", "time": "19:30", "team1": "lsg", "team2": "rcb", "venue": "BRSABV Ekana Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 34, "date": "2025-04-17", "time": "19:30", "team1": "rr", "team2": "gt", "venue": "Sawai Mansingh Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},
    {"matchNo": 35, "date": "2025-04-18", "time": "19:30", "team1": "srh", "team2": "pbks", "venue": "Rajiv Gandhi Intl. Stadium", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None},

    # Playoff placeholders
    {"matchNo": 68, "date": "2025-05-20", "time": "19:30", "team1": "tbd", "team2": "tbd", "venue": "TBD", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None, "type": "Qualifier 1"},
    {"matchNo": 69, "date": "2025-05-21", "time": "19:30", "team1": "tbd", "team2": "tbd", "venue": "TBD", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None, "type": "Eliminator"},
    {"matchNo": 70, "date": "2025-05-23", "time": "19:30", "team1": "tbd", "team2": "tbd", "venue": "TBD", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None, "type": "Qualifier 2"},
    {"matchNo": 71, "date": "2025-05-25", "time": "19:30", "team1": "tbd", "team2": "tbd", "venue": "TBD", "status": "upcoming", "result": None, "team1Score": None, "team2Score": None, "type": "Final"},
]


# Points table derived from completed matches
POINTS_TABLE = [
    {"teamId": "csk", "played": 5, "won": 4, "lost": 1, "nrr": 0.825, "points": 8},
    {"teamId": "rcb", "played": 4, "won": 3, "lost": 1, "nrr": 0.512, "points": 6},
    {"teamId": "kkr", "played": 4, "won": 3, "lost": 1, "nrr": 0.440, "points": 6},
    {"teamId": "srh", "played": 4, "won": 2, "lost": 2, "nrr": 0.680, "points": 4},
    {"teamId": "pbks", "played": 4, "won": 2, "lost": 2, "nrr": 0.210, "points": 4},
    {"teamId": "rr", "played": 4, "won": 2, "lost": 2, "nrr": -0.125, "points": 4},
    {"teamId": "lsg", "played": 3, "won": 2, "lost": 1, "nrr": 0.350, "points": 4},
    {"teamId": "dc", "played": 4, "won": 1, "lost": 3, "nrr": -0.440, "points": 2},
    {"teamId": "mi", "played": 4, "won": 1, "lost": 3, "nrr": -0.310, "points": 2},
    {"teamId": "gt", "played": 4, "won": 0, "lost": 4, "nrr": -1.150, "points": 0},
]

# Default members
MEMBERS = [
    {"id": 1, "name": "Parth", "avatar": "🏏", "topTeams": ["csk", "rcb", "mi", "kkr"]},
    {"id": 2, "name": "Ashu", "avatar": "🎯", "topTeams": ["mi", "kkr", "srh", "rcb"]},
    {"id": 3, "name": "Avilash", "avatar": "⭐", "topTeams": ["rcb", "csk", "rr", "pbks"]},
]
